#!/bin/bash
mode=$(printf 'mount\nunmount\nexit' | dmenu -p "select mode" -i -l 10)
if [ $mode == "mount" ]; then
	drive=$(lsblk --noheadings --raw -o NAME,MOUNTPOINT | awk '$1~/s.*/ && $2 == ""' | dmenu -p "select drive to mount" -i -l 10)
	drive=/dev/$drive
	udisksctl mount -b $drive
fi
if [ $mode == "unmount" ]; then
	drive=$(lsblk --noheadings --raw -o NAME,MOUNTPOINT | awk '$1~/s.*/ && $2 != ""' | awk '{print $1}' | dmenu -p "select drive to unmount" -i -l 10)
	drive=/dev/$drive
	udisksctl unmount -b $drive
fi
if [ $mode == "exit" ]; then
	exit 0
fi
