#!/bin/bash
# dmenu script to mount/unmount usb drives
# dependencies: dmenu, systemd
# edit the lines with udisksctl if you use a distribution without systemd
# like I did on my laptop

menu="dmenu -nb #000000 -nf #aaaaaa -sb #000000 -sf #ff8c00 -i -l 10" #dmenu appearance, edit to your liking
mode=$(printf 'mount\nunmount\nexit' | $menu -p "select mode") #select mode prompt
if [ $mode == "mount" ]; then
	drive=$(lsblk --noheadings --raw -o NAME,MOUNTPOINT | awk '$1~/s.*/ && $2 == ""' | $menu -p "select drive to mount")
	drive=/dev/$drive
	udisksctl mount -b $drive 	#mount the drive with udisksctl
fi
if [ $mode == "unmount" ]; then
	drive=$(lsblk --noheadings --raw -o NAME,MOUNTPOINT | awk '$1~/s.*/ && $2 != ""' | awk '{print $1}' | $menu -p "select drive to unmount")
	drive=/dev/$drive
	udisksctl unmount -b $drive 	#unmount with udisksctl
fi
if [ $mode == "exit" ]; then
	exit 0
fi
