#!/bin/bash

mdir="$HOME/Music"
cmd="dmenu -l 15 -i"

for playlist in $mdir/*; do
	paths=$paths"$playlist\n"
done

plchoice=$(echo -e $paths | awk -F / '{ print $5 }' | $cmd -p "select playlist") &&

if [ "$1" == "-s" ]; then
	termite -e "mpv $mdir/$plchoice --shuffle" & disown
else
	if [ "$1" == "-c" ]; then
		for song in $mdir/$plchoice/*; do
			songs=$songs"$song\n"
		done

		schoice=$(echo -e $songs | awk -F / '{ print $(NF) }' | $cmd -p "select song") &&
		termite -e "mpv $mdir/$plchoice/$schoice" & disown	

	else
		termite -e "mpv $mdir/$plchoice" & disown
	fi

fi


