#!/bin/bash

mdir="$HOME/Music"
cmd="dmenu -l 15 -i"

for playlist in $mdir/*; do
	paths=$paths"$playlist\n"
done

plchoice=$(echo -e $paths | awk -F / '{ print $(NF) }' | $cmd -p "select playlist") &&

if [ "$1" == "-s" ]; then
	termite -e "mpv '$mdir/$plchoice' --shuffle" & disown
else
	if [ "$1" == "-c" ]; then
		for song in $mdir/$plchoice/*; do
			songs=$songs"$song\n"
		done
		
		while true; do
			schoice=$(echo -e $songs | awk -F / '{ print $(NF) }' | $cmd -p "select song")
			if [ -z $schoice ]; then break
			else
				termite -e "mpv '$mdir/$plchoice/$schoice'" 
			fi
		done
	else
		termite -e "mpv '$mdir/$plchoice'" & disown
	fi

fi


