#!/bin/sh
#credit to https://github.com/Bugswriter/
#edited the removal of cache files, because not all were removed properly

guicmd="dmenu -nb #000000 -nf #aaaaaa -sb #000000 -sf #ff8c00 -i -l 15"
if [ -z $1 ]; then
  echo -n "Search query: "; 
  subreddit=$(cat ~/.config/redyt/subreddit.txt | $guicmd -p "Select Subreddit r/"  | cut -d\| -f1 | awk '{$1=$1;print}')
  if [ "$subreddit" == "" ]; then exit; fi
else
  subreddit=$1
fi
echo $subreddit
cachedir=$HOME/.cache/redyt
limit=100
notify-send "📩 Downloading your 🖼️ Memes"
curl -H "User-agent: 'your bot 0.1'" https://www.reddit.com/r/$subreddit/hot.json?limit=$limit > $cachedir/tmp.json && 
imgs=$(cat $cachedir/tmp.json | jq '.' | grep url_overridden_by_dest | grep -Eo "https://.*(jpg|png)\b")

wget -P $cachedir $imgs
notify-send "👍 Download Finished, Enjoy! 😊"
sxiv -a $cachedir/*png $cachedir/*jpg 

rm $cachedir/*jpg* 
rm $cachedir/*png*
rm $cachedir/*gif*
