#!/bin/bash
#dependencies dmenu, mpv, youtube-dl
cmd="dmenu -nb #000000 -sb #000000 -nf #aaaaaa -sf #ff8c00 -i -l 10"
link="https://twitch.tv"
touch $HOME/.streamers.txt

if [ -z $1 ]; then
	streamer=$(cat $HOME/.streamers.txt | $cmd -p "choose streamer")
else
	streamer=$1
fi


if [ -z $streamer ]; then
	notify-send "no streamer chosen!"
	exit 0
fi

while true; do
	if [ ! -z $streamer ]; then
		slink="$link/$streamer"
		notify-send "requesting $slink"
		mpvout="$(streamlink --player mpv $slink best 2>&1)"
		
		offline="$(echo $mpvout | grep "No playable streams found")"	
		if [ "$offline" == "" ]; then
			if [ -z $(grep $streamer $HOME/.streamers.txt) ]; then
				echo $streamer >> $HOME/.streamers.txt
			fi
		else
			notify-send "$streamer is offline! :("
		fi
		
		streamer=$( cat $HOME/.streamers.txt | $cmd -p "choose streamer" )
	else
		notify-send "no streamer chosen!"
		break
		
	fi
	
done
