#!/bin/bash
if [ ! -z $1 ]; then
	touch "$1.tex"
	termite -e "vim $1.tex" & disown	#open vim in new terminal
	convert xc:none -page A4 "$1.pdf"	#create blank pdf
	mupdf "$1.pdf" & disown			#open blank pdf
	while true; do
			inotifywait -q -e modify "$1.tex"
			pdflatex -halt-on-error -interaction=nonstopmode "$1.tex"
			killall -s SIGHUP mupdf		#update mupdf 
	done
else
	echo "needs one argument with the name of the file you want to create."
fi
